---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "White Salmon River Pre and Post Dam Removal: Data Exploration"
subtitle: "https://github.com/kmswann/WhiteSalmon.git"
author: "Kristine Swann"
fontsize: 12pt
mainfont: Times New Roman
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
# Set your working directory
getwd()
swd <- "C:/Users/krist/Box Sync/Spring 2020/R/Environmental_Data_Analytics_2020/WhiteSalmon"

# Load your packages
library(trend)
library(zoo)
library(dataRetrieval);
library (ggplot2);
library(tidyverse);
library(zoo);
library(EGRET); 
library(dplyr); 
library(magrittr); 
library(lubridate);
library(pastecs);
library(leaflet);
library(wesanderson)
library(flextable)
library(officer)

# Set your ggplot theme
mytheme <- theme_classic(base_size = 14) +
theme(axis.text = element_text(color = "black"),
legend.position = "bottom")
theme_set(mytheme)

# Load your datasets
siteNo<-'14123500'#Underwood gage station
pcode = '00060' #discharge cfs
scode="00003" #mean
start.date = "1940-10-01" 
end.date="2019-09-30"
#Load Data
ws<- readNWISdv(siteNumbers = siteNo, parameterCd = pcode, statCd = scode, startDate=start.date, endDate=end.date)
#Rename columns
ws <- renameNWISColumns(ws)
colnames(ws)
```


```{r discharge overview include=FALSE}

#################################################################################################
#LOOKING AT DISCHARGE RAW
#################################################################################################
stat.desc(month.flow)

Discharge <- ggplot(ws, aes(x=Date, y= Flow, colour = Flow_cd)) +
  geom_line()+
  labs(x = "", y= "Discharge (cfs)", colour = 'Confidence')+
  scale_color_manual(values = wes_palette("FantasticFox1",5)[3:5])+
 geom_vline(xintercept = as.Date("2011-10-26"), na.rm=FALSE, show.legend=NA, lty=2, col="black", lwd=1)+
  geom_text(x = as.Date("2010-01-01"), y = 15000, label = "Decomissioning", hjust = 1, col="#b41820", fontface = "bold", na.rm=FALSE, show.legend = FALSE)+
    geom_text(x = as.Date("2010-04-01"), y = 14200, label = "begins", hjust = 1, col="#b41820", fontface = "bold", na.rm=FALSE, show.legend = FALSE)

print(Discharge)

```
#### Figure 2: Discharge over time with USGS QA/QC codes

#### Table 1: Descriptive statistics based on time frame subsets
```{r descriptive stats table include=FALSE}
#################################################################################################
#PULLING SUMMARY STATS OUT OF DATA BASED ON TIME PERIODS
#################################################################################################

#Create data frame
sum.stats <- as.data.frame(matrix(nrow=8, ncol=5))
  colnames(sum.stats) <- c("Statistics","p1940-2019","p2003-2019", "p2003-2011","p2011-2019")
#First column
   sum.stats$Statistics <- c("Min","10th percentile","25th percentile","Median","Mean","75th percentile", "90th percentile","Max")
   
#Function to fill in second column
  #data.frame[row number, column number]
gen_stats = function(data, column.no){
  sum.stats[1,column.no] <- min(data$Flow);               
  sum.stats[2,column.no] <- quantile(data$Flow, 0.10);             sum.stats[3,column.no] <- quantile(data$Flow, 0.25);
  sum.stats[4,column.no] <- median(data$Flow);                     sum.stats[5,column.no] <- mean(data$Flow);
  sum.stats[6,column.no] <- quantile(data$Flow, 0.75);             sum.stats[7,column.no] <- quantile(data$Flow, 0.90);
  sum.stats[8,column.no] <- max(data$Flow);               
  
  return(sum.stats)
}
sum.stats <- gen_stats(ws, 2)
sum.stats$`p1940-2019` <- round(sum.stats$`p1940-2019`,3)
sum.stats

#Subset data and rerun function
ws.prepost <- subset(ws, Date>="2003-10-01");          summary(ws.prepost$Date)
ws.postdr <- subset(ws, Date>"2011-11-01");         summary(ws.postdr$Date)
ws.predr <- subset(ws, Date >="2003-10-01" & Date<="2011-09-30");         summary(ws.predr$Date)

#call the function to calculate summary statistics
sum.stats <- gen_stats(ws.prepost,3)
sum.stats <- gen_stats(ws.predr,4)
sum.stats <- gen_stats(ws.postdr,5)

#round values
sum.stats[,c(2:4)]<- round(sum.stats[,c(2:4)],3)
  sum.stats
table1<- flextable(sum.stats)
table1<- autofit(table1)
print(table1)

```

```{r seasonal variation include=FALSE}
#################################################################################################
#LOOKING AT SEASONAL VARIATION
#################################################################################################

#Separate Date into Years/Months
ws$Year <- year(ws$Date)
ws$Month <- month(ws$Date)

month.flow.historic <- ws %>%
               filter(Date>="1940-10-01") %>%
               group_by(Month) %>%
               summarise('1941 to 2019' = mean(Flow, na.rm=T)) %>%  
               round(3)

month.flow.pre <- ws %>%
               filter(Date<="2011-09-30" & Date >="2003-10-01") %>%
               group_by(Month) %>%
               summarise('2004 to 2011' = mean(Flow, na.rm=T)) %>%  
               round(3)

month.flow.post <- ws %>%
               filter(Date>="2011-11-01") %>%
               group_by(Month) %>%
               summarise('2012 to 2019' = mean(Flow, na.rm=T)) %>%  
               round(3)



#create dataframe and bind 3 tables together
month.flow <- as.data.frame(cbind(month.flow.historic, 
                                  month.flow.pre[, 2], 
                                  month.flow.post[, 2])) 


#Fix up the dataframe for plotting 

month.flow <- arrange(month.flow, Month) #automatically sorts ascending

# Reshape month flow for ggplot (make long)
month.flow.long <- data.frame() # empty dataframe
for (g in c("1941 to 2019", "2004 to 2011", "2012 to 2019")) {
  
  # Keep slice of dataframe
  tdf <- month.flow[c('Month', g)]
  
  # Create label
  tdf$group <- g
  
  # Rename columns
  names(tdf) <- c('Month', 'Flow', 'Group')
  
  # Bind to month.flow.long
  month.flow.long <- rbind(month.flow.long, tdf)
}

# Plot results
seasonalplot <- 
ggplot(data = month.flow.long,
       aes(x = Month, y = Flow, colour = Group)) +
  geom_point(size = 2) +
  geom_line() +
 scale_x_continuous( breaks = seq(1, 12, by = 1))+
  scale_color_manual(values = wes_palette("FantasticFox1",5)[2:5])+
  labs(x = 'Month', y = 'Mean streamflow (cfs)', colour = 'Time period (Water Years)')

print(seasonalplot)


```

#### Figure 3: Monthly averages by subset time periods