---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "White Salmon River Pre and Post Dam Removal: 7Q10 Low Flows"
subtitle: "https://github.com/kmswann/WhiteSalmon.git"
author: "Kristine Swann"
fontsize: 12pt
mainfont: Times New Roman
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
# Set your working directory
getwd()
swd <- "C:/Users/krist/Box Sync/Spring 2020/R/Environmental_Data_Analytics_2020/WhiteSalmon"

# Load your packages
library(dataRetrieval); library(EGRET); library (ggplot2);library(dplyr); library(magrittr); library(lubridate); library(viridis);library(nlme);library(piecewiseSEM); library(TTR); library(wesanderson)

# Set your ggplot theme
mytheme <- theme_classic(base_size = 14) +
theme(axis.text = element_text(color = "black"),
legend.position = "bottom")
theme_set(mytheme)

# Load your datasets
siteNo<-'14123500'#Underwood gage station
pcode = '00060' #discharge cfs
scode="00003" #mean
start.date = "1940-10-01" 
end.date="2019-09-30"
#Load Data
ws<- readNWISdv(siteNumbers = siteNo, parameterCd = pcode, statCd = scode, startDate=start.date, endDate=end.date)
#Rename columns
ws <- renameNWISColumns(ws)
colnames(ws)

#write.csv(ws, "./Data/WhiteSalmon", row.names=FALSE)
```

## R Markdown



```{r 7q10}
#subset the data
prepost <- subset(ws, Date>="2003-10-01")
predr <- subset(ws, Date>="2003-10-01" & Date<= "2011-09-30")
postdr <- subset(ws, Date>= "2011-11-01")

Fun_7q10 = function(data, ndays){   
data$Q7 <- SMA(data$Flow, ndays) #the first 7 observations are not included
  
  #For each year, calculate the minimum Q7
  data$Year <- year(data$Date);  data$Month <- month(data$Date)
  
  #Maximum Annual Flow
  low.flow <- data %>%
    group_by(Year) %>%
    summarise(MinQ7 = min(Q7, na.rm=T), n=n()) %>%  round(3)
  
  low.flow <- as.data.frame(low.flow);  
  #remove rows missing more than 10% of data
  low.flow <- subset(low.flow, n>=(365-365*.1))
  
  #rank flows
  low.flow <- arrange(low.flow, (MinQ7)); low.flow[1:5,]
  low.flow$Rank <- rank(low.flow$MinQ7); low.flow[1:5,]
  
  n.years <- dim(low.flow)[1]; n.years
  low.flow$ReturnInterval <- (n.years+1)/low.flow$Rank; low.flow[1:5,]
  low.flow$AnnualProb <- round(1/low.flow$ReturnInterval*100,3);  low.flow[1:5,]
  
  return (low.flow)
} #end function

low.flow.historic <-Fun_7q10(ws,7)
low.flow.prepost <- Fun_7q10(prepost,7)
low.flow.pre <- Fun_7q10(predr,7)
low.flow.post <- Fun_7q10(postdr,7)

```

## 

```{r Plotting low flows and regressions, echo=FALSE}
#plot the data
par(mar = c(5,5,3,5)) #set plot margins
plot(low.flow.historic$AnnualProb, low.flow.historic$MinQ7, type='n', yaxt="n", xlim=c(1,100),
     ylab="Min Q7 Streamflow (cfs)", xlab = 'Probability of smaller flows')
axis(2, las=2, cex.axis=0.9)
points(low.flow.historic$AnnualProb, low.flow.historic$MinQ7, col=rgb(0,0,0,0.8), cex=0.8, pch=19)  
  abline(v=10, lty=4, col="black")

#linear regression
linear = lm(MinQ7 ~ AnnualProb , data = low.flow.historic);
  summary(linear)

#exponential regression
exp.lm = lm(log(MinQ7) ~ (AnnualProb), data=low.flow.historic)
  summary(exp.lm)
  
#linear is pretty close
  x.est <- as.data.frame(seq(0,100,10)); colnames(x.est)<-"AnnualProb"
  y.est <- predict(linear,x.est, interval="confidence")
  y.est <- as.data.frame(y.est)
    y.est.exp <- as.data.frame(exp(predict(exp.lm,x.est, interval="confidence")))
  
  #Add to plot
  lines(x.est$AnnualProb, y.est$fit, col="red", lty=3, lwd=2);
  lines(x.est$AnnualProb, y.est.exp$fit, col="darkgreen", lty=5, lwd=2)

  #What is the 7Q10 low flow value?
low.7Q10 <- predict(linear,filter(x.est,AnnualProb==10),interval="confidence"); low.7Q10

abline(h=low.7Q10[1], col="black", lty=2, lwd=2)

```

```{r Plotting low flows occurrences, echo=FALSE}
low.days <- subset(ws, Flow <= low.7Q10[1]); dim(low.days)
  n.years <- length(unique(low.days$Year))
  print(paste0("Probability of occurrence: ", round(n.years/length(unique(ws$Year))*100,2)))
  
  #plot low flow days
  plot(ws$Date, ws$Flow, type='n', yaxt="n", ylim=c(0,8000),
       ylab="Streamflow (cfs)", xlab = '')
  axis(2, las=2, cex.axis=0.9)
  lines(ws$Date, ws$Flow, lwd=1, col=rgb(0,0,1,0.3))
  
  points(low.days$Date, low.days$Flow, col=rgb(1,0,0,0.8), pch=19)  
  abline(v=c(as.Date("2011-10-26")), lty=2, col="black", lwd=3)
  abline(h=low.7Q10, col="red", lty=4)
  
```

```{r Return Interval, echo=FALSE}
#Plot data
par(mar = c(5,5,3,5)) #set plot margins
  plot(low.flow.post$AnnualProb, low.flow.post$MinQ7, type='n', yaxt="n", xlim=c(1,100), ylim=c(300,1000),
       ylab="Min Q7 Streamflow (cfs)", xlab = 'Annual Probability of Exceedance')
  axis(2, las=2, cex.axis=0.9)
  points(low.flow.post$AnnualProb, low.flow.post$MinQ7, col=rgb(0.7,0.5,0,0.8), cex=1, pch=19)  
  abline(v=10, lty=4, col="black")
  
  #linear regression
  linear.post = lm(MinQ7 ~ AnnualProb , data = low.flow.post);
    summary(linear.post)
  #exponential regression
  exp.lm.post = lm(log(MinQ7) ~ (AnnualProb), data=low.flow.post)
    summary(exp.lm.post) 
      #r2 is similar - you can choose either one
  y.est.post <- predict(linear.post,x.est, interval="confidence")
  y.est.post <- as.data.frame(y.est.post)
  y.est.exp.post <- as.data.frame(exp(predict(exp.lm.post,x.est, interval="confidence")))
  
  #Add to plot
  #lines(x.est$AnnualProb, y.est.post$fit, col="red", lty=3,lwd=2);
  #lines(x.est$AnnualProb, y.est.exp.post$fit, col="darkgreen", pch=4)
  
#What is the 7Q10 low flow value?
  low.7Q10.post <- predict(linear.post,filter(x.est,AnnualProb==10),interval="confidence"); low.7Q10.post
    abline(h=low.7Q10.post[1], col=rgb(0.7,0.5,0), lty=2, lwd=2)
    #abline(h=low.7Q10.post, col="black", lty=4)
  
#add original low flow value
  abline(h=low.7Q10[1], col="red", lty=4)
  points(low.flow.historic$AnnualProb, low.flow.historic$MinQ7, col=rgb(1,0,0,0.8), cex=0.6, pch=19)  

legend("top", c("Post Dam Removal Annual Low Flow", "Post Dam Removal 7Q10", "POR Annual Low Flow", "POR 7Q10"), col=c("goldenrod3","goldenrod3","red","red"),
       pch=c(19,NA,19,NA), lty=c(0,2,0,4))
```

```{r Days where low flow was exceeded using new 7q10, echo=FALSE}
#plot low flow days
plot(ws$Date, ws$Flow, type='n', yaxt="n", ylim=c(300,1000),
     ylab="Streamflow (cfs)", xlab = '')
axis(2, las=2, cex.axis=0.9)
lines(ws$Date, ws$Flow, lwd=1, col=rgb(0,0,1,0.3))

#subset data to only include low flow exceedances
low.days.post <- subset(ws, Flow <= low.7Q10.post[1]); dim(low.days.post)
#plot points and ablines
points(low.days.post$Date, low.days.post$Flow, col=rgb(1,0,0,0.6), pch=19, cex=0.8)  
abline(v=c(as.Date("2011-10-26")), lty=2, col="black", lwd=3)
abline(h=low.7Q10.post[1], col="red", lty=4)
points(low.days$Date, low.days$Flow, col=rgb(0.7,0,0,0.6), pch=19)  
abline(h=low.7Q10[1], col="darkred", lty=4)
n.years.post <- length(unique(low.days.post$Year))


#create table
RI.table <- as.data.frame(matrix(nrow=2, ncol=5));    
#provide column names
colnames(RI.table) <- c("Date.Range", "7Q10_cfs","No_Years","Annual_Prob","AdjustedR2")
#fill columns with relevant data
  RI.table$Date.Range <- c("1941-2019","2012-2019")
  RI.table$`7Q10_cfs` <- c(round(low.7Q10[1],3), round(low.7Q10.post[1],3))
  RI.table$No_Years <- c(n.years.por, n.years.post)
  RI.table$Annual_Prob <- c(round(n.years.por/length(unique(ws$Year))*100,2), round(n.years.post/length(unique(ws$Year))*100,2))
  RI.table$AdjustedR2 <- c(summary(exp.lm)$adj.r.squared, summary(exp.lm.post)$adj.r.squared)
#Look at the table
RI.table
```

